import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState} from "react";

import * as cheerio from 'cheerio';

export default function Home() {
  
  const [name, setName] = useState('');
  const [hairColor, setHairColor] = useState('');
  const [favouriteFood, setFavouriteFood] = useState('');
  const handleNameChange = (event) => {
    const value = event.target.value;

    setName(value);
  }

  const handleHairColorChange = (event) => {
    const value = event.target.value;

    setHairColor(value);
  }

  const handleFavouriteFoodChange = (event) => {
    const value = event.target.value;

    setFavouriteFood(value);
  }

  const handleSubmit = async () => {
    console.log(name);
    console.log(hairColor);
    console.log(favouriteFood);
    const data = {
      name,
      hairColor,
      favouriteFood
    }
    const body = JSON.stringify(data);
    const requestOptions = {
      method: 'POST',
      headers: {
        'Content-Type': "application/json"
      },
      body,
    }

    const response = await fetch('http://localhost:3000/api/flamingo', requestOptions);
    const json = await response.json();

    console.log(json);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <h1>Hey</h1>
      </Head>
      <p>
        Name
        <input type="text" value={name} onChange={handleNameChange}></input>
      </p>

      <p>
        Hair Color
        <input type="text" value={hairColor} onChange={handleHairColorChange}></input>
      </p>

      <p>
        Favourite Food
        <input type="text" value={favouriteFood} onChange={handleFavouriteFoodChange}></input>
      </p>

      <button onClick={handleSubmit}>Add</button>

    </div>
  )
}


export async function getServerSideProps() {
 
                                      
  
  return {
    props: {}
  }
}
